### ISSUE TITLE
.env.web file?

### ISSUE THREAD

**Issue by kanderg** [ashirt-ops/ashirt-server#1050]
I am setting up the PROD version of ashirt b/c the dev version was very interesting to play with but the instructions for the initial logon seems to be confusing the heck out of me.

" After the first users are registered the admin should change AUTH_SERVICES_ALLOW_REGISTRATION=ashirt to #AUTH_SERVICES_ALLOW_REGISTRATION=ashirt in .env.web", I am able to get the initial admin account created no issues but when looking for the .env.web file to comment out there does not appear to be a file with that name.

Am I missing something?

**Comment by jrozner** [comment]
@kanderg Saw in discord that you figured this out. Is this ok to close?

**Comment by kanderg** [comment]
Yes I apologize I forgot to go back and close this. It was an id10 error with a spelling on one of the s3s.
