### ISSUE TITLE
Super admins don't see all operations in admin area

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt-server#17]
The list of operations in the admin area only displays operations that the user is a member of.

**Comment by JoelAtDeluxe** [comment]
This is actually fixed in PR #14, specifically this commit:
https://github.com/theparanoids/ashirt/pull/14/commits/bbc4844c672a278a6964daa5b757ead95b900a91

**Comment by jrozner** [comment]
Perfect. Will get those PRs reviewed and verified.

**Comment by jrozner** [comment]
Confirmed fixed in master from #14
