### ISSUE TITLE
Migrate away from gorilla

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt-server#750]
It looks like the set of Gorilla libraries are no longer maintained https://github.com/gorilla/#gorilla-toolkit. We make use of a number of the libraries including: mux, sessions, csrf, and securecookie. Given how stable and simple the code is for most of these this probably isn't a rush but we should look to move off of Gorilla when convenient.

Looking at the code things are pretty abstracted and it likely wouldn't be a significant lift, at least for the mux. If the new mux we move to doesn't have it's own middleware to handle the others we may need to build our own for find alternatives.

**Comment by jkennedyvz** [comment]
Closed with https://github.com/ashirt-ops/ashirt-server/pull/843
