### ISSUE TITLE
Build support discoverable credentials

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt-server#837]
When using discoverable credentials we shouldn't need to supply a username in order to log in. We need to determine if there is ever a workflow that we're going to use that doesn't require discoverable credentials. We currently don't support webauthn as a second factor for username/passwords and we likely never will need to. We're hopefully more likely to completely remove username/password in favor of passwordless as some point.

**Comment by TylerNoblett** [comment]
fwiw we can close this issue now that we've added [discoverable login](https://github.com/ashirt-ops/ashirt-server/pull/931)
