### ISSUE TITLE
Additional editable timestamp property on Evidence

### ISSUE THREAD

**Issue by audibleblink** [ashirt-ops/ashirt-server#894]
Perfect evidence logging hygiene increases in difficulty as more people collaboratively work on an Operation.
Whether something was logged incorrectly, or just missed entirely, there's currently no first-class way to remedy this. As a workaround, the timestamp is just noted as a correction in the description field.

The preservation of the timeline is definitely a big value-add of ashirt's, so perhaps it's important to those who receive these timelines as a deliverable, to know that it hasn't been modified. So rather than editing an evidence's timestamp or inserting new evidence at arbitrary times, I propose an additional field in the Evidence model. 

Differentiation between when an action happened and when it was logged would give users the ability to view the timeline sorted by either.

Having a time-picker for a property of something like `occurred_at` would allow for fixups and late additions. Its default value in the modal could be the same as the `created_at` timestamp so as to not inconvenience users not needing this ability. The time-picker should exist in the web's evidence creation modal as well as the edit modal.

Too, it would be helpful if the operation's evidence page allowed for sorting of either timestamp. 
The new timestamp should also exist in exported information.

**Comment by audibleblink** [comment]
I just looked through the code to gauge the lift and saw you already use `occurred_at` the default timestamp the timeline sorts by. I'm struggling to think of a different name for the editable field but wanted to clear up the confusion since my proposed property name already exists.

**Comment by jrozner** [comment]
We're open to discussion about this. It's designed as is to prevent tampering with data and preserve the data. We've definitely run into issues where evidence had to be captured later and the timeline ends up being out of order. Like you mentioned there is an occurred_at field which is what we currently use for sorted evidence. When evidence is created in the web UI that defaults to the same value as created_at (the current time). When using a client like ASHIRT, the occurred_at timestamp is the timestamp that the client records and the created_at is the time the server creates the evidence. We probably want to be able to maintain that. Maybe we can add another adjusted_timestamp field that is user controllable and we can sort by that; defaulting to the value in occurred_at if adjusted_timestamp isn't set?

1. Would you want everyone with write permissions to be able to adjust a timestamp or only admins of an operation?
2. Would you want to see some sort of UI icon or other denotation that the timestamp for a specific evidence has been adjusted in the timeline?

**Comment by audibleblink** [comment]
Anyone with write should be able to modify the adjusted_at timestamp.

I think when viewing a single piece of evidence where the timestamps differ, a subdued timestamp or marker could appear under the description.

Having a button or toggle in the menu bar (or some other prominent place) that states whether the current view is being sorted by occurrence/adjusted date would be ideal.
